genome: "workflow/resources/genome/schMedA2_h1.fa"
annotation: "workflow/resources/genome/schMedA2_h1.ENCODE_hybrid_annot.sort.gff3"
rrna_db: "/projects/ferenc.kagan/Databases/rRNA_databases_v4/smr_v4.3_sensitive_db.fasta"
kraken2_db: "/projects/ferenc.kagan/Databases/kraken_plan/"
threads: 30
PE_ext: "_R{pair}.fastq.gz"
